name: Deploy Pages

on:
  push:
    paths:
      - 'pub/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pub

      - name: Deploy
        uses: actions/deploy-pages@v4
